- name: Add AnyDesk repository key
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    state: present

- name: Add AnyDesk repository
  apt_repository:
    repo: deb http://deb.anydesk.com/ all main
    state: present

- name: Update APT after adding AnyDesk repository
  apt:
    update_cache: yes

- name: Install AnyDesk
  apt:
    name: anydesk
    state: present
