- name: Install Zsh
  apt:
    name: zsh
    state: present

- name: Change default shell to Zsh for the current user
  shell: chsh -s $(which zsh) "{{ ansible_user_id }}"

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: /home/{{ ansible_user_id }}/.oh-my-zsh

- name: Set up .zshrc
  template:
    src: zshrc.j2
    dest: /home/{{ ansible_user_id }}/.zshrc
  become: yes
  become_user: "{{ ansible_user_id }}"

