- name: Download 1Password .deb package
  get_url:
    url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    dest: /tmp/1password-latest.deb

- name: Install 1Password
  apt:
    deb: /tmp/1password-latest.deb
    state: present
